"'STW AUDIT SHEET_SETTINGS' As screen":

    Label1_30 As label:
        Align: =Align.Right
        Color: =RGBA(255, 255, 255, 1)
        DisabledFill: =RGBA(141, 198, 63, 1)
        Fill: =RGBA(0, 134, 208, 1)
        FontWeight: =FontWeight.Bold
        Height: =67
        Size: =20
        Text: =""
        Width: =640
        Y: =1069
        ZIndex: =1

    Label1_25 As label:
        Align: =Align.Right
        Color: =RGBA(255, 255, 255, 1)
        DisabledFill: =RGBA(141, 198, 63, 1)
        Fill: =RGBA(0, 134, 208, 1)
        FontWeight: =FontWeight.Bold
        Height: =67
        Size: =20
        Text: ="STW Audit  "
        Width: =640
        Y: =16
        ZIndex: =3

    Image1_9 As image:
        Height: =39
        Image: ='mas-holdings-logo-2ACA338CD6-seeklogo.com'
        Width: =184
        X: =13
        Y: =34
        ZIndex: =4

    Label2_31 As label:
        Align: =Align.Right
        Font: =Font.'Lato Black'
        FontWeight: =FontWeight.Bold
        Height: =37
        Text: ="IE DIGITALIZATION"
        Width: =180
        X: =436
        Y: =1099
        ZIndex: =6

    Label2_30 As label:
        Align: =Align.Right
        FontWeight: =FontWeight.Semibold
        Height: =37
        Size: =12
        Text: ="Designed by "
        X: =466
        Y: =1076
        ZIndex: =7

    Icon1_12 As icon.BackArrow:
        Color: =RGBA(0, 0, 0, 1)
        Height: =40
        Icon: =Icon.Home
        OnSelect: =Navigate('STW AUDIT SHEET_1')
        Width: =40
        X: =26
        Y: =1085
        ZIndex: =8

    Icon11 As icon.Person:
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(166, 166, 166, 1)
        Height: =166
        Icon: =Icon.Person
        OnSelect: |-
            =If(
                LookUp('IE Department Name list',User().Email='Email IE','Responsible for STW'.Value) = "STW",
                Set(varAdminButton1,true),
                Set(varAdminAccess,"You don't have permission to access Admin section !!!") And
                Set(varAdminMsg,true)
            )  
            
            //Set(varAdminButton1,true)
        Width: =139
        X: =35
        Y: =123
        ZIndex: =9

    Label10 As label:
        Align: =Align.Center
        DisplayMode: =DisplayMode.View
        FontWeight: =FontWeight.Bold
        Height: =45
        Size: =20
        Text: ="Admin"
        Width: =139
        X: =35
        Y: =306
        ZIndex: =10

    Button9 As button:
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(166, 166, 166, 1)
        FontWeight: =FontWeight.Bold
        Height: =137
        OnSelect: |-
            =Set(varStyle,false);
            Set(varSectionAndModule,true)
        Size: =20
        Text: ="Section And Module"
        Visible: =varAdminButton1
        Width: =139
        X: =273
        Y: =137
        ZIndex: =11

    Button9_1 As button:
        Color: =RGBA(0, 0, 0, 1)
        Fill: =RGBA(166, 166, 166, 1)
        FontWeight: =FontWeight.Bold
        Height: =137
        OnSelect: |-
            =Set(varSectionAndModule,false);
            Set(varStyle,true)
        Size: =20
        Text: ="Style"
        Visible: =varAdminButton1
        Width: =139
        X: =435
        Y: =137
        ZIndex: =12

    "GallerySectionAndModule As gallery.'BrowseLayout_Vertical_TwoTextVariant_ver4.0'":
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Default: =varGallerySAM
        Fill: =RGBA(202, 202, 202, 1)
        Height: =381
        Items: ='Section And Module'
        Layout: =Layout.Vertical
        OnSelect: =ResetForm(FormSectionAndModule);EditForm(FormSectionAndModule)
        TemplateFill: =If(ThisItem.IsSelected,ColorFade(RGBA(98, 100, 167, 1),-2%),RGBA(0, 0, 0, 0))
        TemplatePadding: =0
        TemplateSize: =80
        Visible: =varSectionAndModule
        Width: =567
        X: =35
        Y: =363
        ZIndex: =13

        Title5 As label:
            Height: =51
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Section
            VerticalAlign: =VerticalAlign.Top
            Width: =196
            X: =27
            Y: =31
            ZIndex: =1

        Subtitle5 As label:
            Height: =54
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.'Module No'
            VerticalAlign: =VerticalAlign.Top
            Width: =75
            X: =400
            Y: =31
            ZIndex: =2

        Separator5 As rectangle:
            Height: =1
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =4

        Icon12 As icon.Trash:
            Height: =35
            Icon: =Icon.Trash
            OnSelect: =Remove('Section And Module',ThisItem)
            Width: =35
            X: =490
            Y: =31
            ZIndex: =5

    FormSectionAndModule As form:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        DataSource: ='Section And Module'
        Fill: =RGBA(202, 202, 202, 1)
        Height: =288
        Item: =GallerySectionAndModule.Selected
        NumberOfColumns: =1
        OnFailure: =Notify("Form does not submit",NotificationType.Error)
        OnSuccess: =Notify("You Have Succussfully entered data",NotificationType.Success);
        Visible: =varSectionAndModule
        Width: =567
        X: =35
        Y: =770
        ZIndex: =14

        Section_DataCard1_1 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="Section"
            Default: =ThisItem.Section
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Section And Module'],DataSourceInfo.DisplayName,"Section")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@'Section And Module'], DataSourceInfo.MaxLength, "Section")
            Required: =false
            Update: =DataCardValue27_1.Text
            Width: =584
            X: =0
            Y: =0
            ZIndex: =15

            DataCardKey23_1 As label:
                AutoHeight: =true
                Color: =RGBA(0, 0, 0, 1)
                FontWeight: =FontWeight.Bold
                Height: =34
                Size: =15
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue27_1 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey23_1.Y + DataCardKey23_1.Height + 5
                ZIndex: =2

            ErrorMessage27_1 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue27_1.Y + DataCardValue27_1.Height
                ZIndex: =3

            StarVisible20_1 As label:
                Align: =Align.Center
                Height: =DataCardKey23_1.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey23_1.Y
                ZIndex: =4

        "'Module No_DataCard1_1' As typedDataCard.textualEditCard":
            BorderStyle: =BorderStyle.Solid
            DataField: ="ModuleNo"
            Default: =ThisItem.'Module No'
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Section And Module'],DataSourceInfo.DisplayName,"ModuleNo")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@'Section And Module'], DataSourceInfo.MaxLength, "ModuleNo")
            Required: =false
            Update: =DataCardValue28_1.Text
            Width: =584
            X: =0
            Y: =1
            ZIndex: =15

            DataCardKey24_1 As label:
                AutoHeight: =true
                Color: =RGBA(0, 0, 0, 1)
                FontWeight: =FontWeight.Bold
                Height: =34
                Size: =15
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue28_1 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey24_1.Y + DataCardKey24_1.Height + 5
                ZIndex: =2

            ErrorMessage28_1 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue28_1.Y + DataCardValue28_1.Height
                ZIndex: =3

            StarVisible23_1 As label:
                Align: =Align.Center
                Height: =DataCardKey24_1.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey24_1.Y
                ZIndex: =4

    "GalleryStyle As gallery.'BrowseLayout_Vertical_TwoTextVariant_ver4.0'":
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        Default: =varGalleryST
        Fill: =RGBA(202, 202, 202, 1)
        Height: =456
        Items: ='Lockup Details'
        Layout: =Layout.Vertical
        OnSelect: =ResetForm(FormStyle);EditForm(FormStyle)
        TemplateFill: =If(ThisItem.IsSelected,ColorFade(RGBA(98, 100, 167, 1),-2%),RGBA(0, 0, 0, 0))
        TemplatePadding: =0
        TemplateSize: =80
        Visible: =varStyle
        Width: =567
        X: =35
        Y: =363
        ZIndex: =17

        Title5_1 As label:
            Height: =51
            OnSelect: =Select(Parent)
            PaddingBottom: =0
            PaddingLeft: =0
            PaddingRight: =0
            PaddingTop: =0
            Text: =ThisItem.Style
            VerticalAlign: =VerticalAlign.Top
            Width: =196
            X: =27
            Y: =31
            ZIndex: =1

        Separator5_1 As rectangle:
            Height: =1
            OnSelect: =Select(Parent)
            Width: =Parent.TemplateWidth
            Y: =Parent.TemplateHeight - 1
            ZIndex: =4

        Icon12_1 As icon.Trash:
            Height: =35
            Icon: =Icon.Trash
            OnSelect: =Remove('Lockup Details',ThisItem)
            Width: =35
            X: =490
            Y: =31
            ZIndex: =5

    Group13 As group:
        Height: =5
        Width: =5
        X: =-930
        Y: =-360
        ZIndex: =17

        Button10 As button:
            Fill: =ColorFade(RGBA(98, 100, 167, 1),-2%)
            OnSelect: |-
                =ResetForm(FormSectionAndModule);NewForm(FormSectionAndModule);Set(varGallerySAM,Blank());Set(varGallerySAM,{});
                Refresh('Section And Module')
            Text: ="Add"
            Visible: =varSectionAndModule
            X: =250
            Y: =994
            ZIndex: =15

        Button10_1 As button:
            Fill: =ColorFade(RGBA(98, 100, 167, 1),-2%)
            OnSelect: |-
                =SubmitForm(FormSectionAndModule);
                Refresh('Section And Module')
            Text: ="Update"
            Visible: =varSectionAndModule
            X: =427
            Y: =994
            ZIndex: =16

    FormStyle As form:
        BorderColor: =RGBA(0, 0, 0, 1)
        BorderThickness: =1
        DataSource: ='Lockup Details'
        Fill: =RGBA(202, 202, 202, 1)
        Height: =200
        Item: =GalleryStyle.Selected
        NumberOfColumns: =1
        OnFailure: =Notify("Form does not submit",NotificationType.Error)
        OnSuccess: =Notify("You Have Succussfully entered data",NotificationType.Success);
        Visible: =varStyle
        Width: =567
        X: =35
        Y: =839
        ZIndex: =18

        Style_DataCard1_1 As typedDataCard.textualEditCard:
            BorderStyle: =BorderStyle.Solid
            DataField: ="Style"
            Default: =ThisItem.Style
            DisplayMode: =Parent.DisplayMode
            DisplayName: =DataSourceInfo([@'Lockup Details'],DataSourceInfo.DisplayName,"Style")
            Fill: =RGBA(0, 0, 0, 0)
            Height: =50
            MaxLength: =DataSourceInfo([@'Lockup Details'], DataSourceInfo.MaxLength, "Style")
            Required: =false
            Update: =DataCardValue31_1.Text
            Width: =585
            X: =0
            Y: =0
            ZIndex: =20

            DataCardKey27_1 As label:
                AutoHeight: =true
                Color: =RGBA(0, 0, 0, 1)
                FontWeight: =FontWeight.Bold
                Height: =34
                Size: =15
                Text: =Parent.DisplayName
                Width: =Parent.Width - 60
                Wrap: =false
                X: =30
                Y: =10
                ZIndex: =1

            DataCardValue31_1 As text:
                BorderColor: =If(IsBlank(Parent.Error), Parent.BorderColor, Color.Red)
                Default: =Parent.Default
                DelayOutput: =true
                DisplayMode: =Parent.DisplayMode
                MaxLength: =Parent.MaxLength
                PaddingLeft: =5
                RadiusBottomLeft: =0
                RadiusBottomRight: =0
                RadiusTopLeft: =0
                RadiusTopRight: =0
                Tooltip: =Parent.DisplayName
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardKey27_1.Y + DataCardKey27_1.Height + 5
                ZIndex: =2

            ErrorMessage31_1 As label:
                AutoHeight: =true
                Height: =10
                Live: =Live.Assertive
                PaddingBottom: =0
                PaddingLeft: =0
                PaddingRight: =0
                PaddingTop: =0
                Text: =Parent.Error
                Visible: =Parent.DisplayMode=DisplayMode.Edit
                Width: =Parent.Width - 60
                X: =30
                Y: =DataCardValue31_1.Y + DataCardValue31_1.Height
                ZIndex: =3

            StarVisible26_1 As label:
                Align: =Align.Center
                Height: =DataCardKey27_1.Height
                Text: ="*"
                Visible: =And(Parent.Required, Parent.DisplayMode=DisplayMode.Edit)
                Width: =30
                Wrap: =false
                Y: =DataCardKey27_1.Y
                ZIndex: =4

    Group13_1 As group:
        Height: =5
        Width: =5
        X: =-930
        Y: =-360
        ZIndex: =21

        Button10_2 As button:
            Fill: =ColorFade(RGBA(98, 100, 167, 1),-2%)
            OnSelect: =ResetForm(FormStyle);NewForm(FormStyle);Set(varGalleryST,Blank());Set(varGalleryST,{});Refresh('Lockup Details')
            Text: ="Add"
            Visible: =varStyle
            X: =250
            Y: =973
            ZIndex: =19

        Button10_3 As button:
            Fill: =ColorFade(RGBA(98, 100, 167, 1),-2%)
            OnSelect: =SubmitForm(FormStyle);Refresh('Lockup Details')
            Text: ="Update"
            Visible: =varStyle
            X: =427
            Y: =973
            ZIndex: =20

